export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
export const FETCH_ALL_SHOPS = "FETCH_ALL_SHOPS";
export const FETCH_ALL_BRANDS = "FETCH_ALL_BRANDS";
export const FETCH_ONEPRODUCT = "FETCH_ONEPRODUCT";
